name: CI
on: [push, pull_request]
jobs:
  build-objexport:
    name: Build objexport
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Restore
        working-directory: tools/objexport
        run: dotnet restore
      - name: Build
        working-directory: tools/objexport
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: tools/objexport
        run: |
          dotnet run --no-restore || ec=$?
          if [ $ec = 1 ]; then
              exit 0
          else
              exit 1
          fi
  build-objects:
    name: Build objects
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create objects.zip
      run: ./package
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "OpenRCT2 Objects"
        path: artifacts/objects.zip
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        fail_on_unmatched_files: true
        files: artifacts/objects.zip
